import getSitePages from './get-site-pages'
import makeIssues from './make-issues'
import {createIssues, closeGeneratedIssues, getUser} from './gh-api'

import type Repo from './__types__/Repo'

async function main() {
  const distro = 'rolling'
  const baseUrl = 'https://docs.ros.org/en/'
  const sections: string[] = ['Install', 'Tutorials', 'How-to-guide']
  const platforms = ['ubuntu', 'windows']
  const repo: Repo = {
    owner: 'audrow',
    name: 'humble-tcm-example',
  }
  const generatedStamp = `generated by @${await getUser()}`

  const pages = await getSitePages(distro, baseUrl, sections)
  const issues = makeIssues(pages, platforms, generatedStamp)
  console.log(await getUser())
  await createIssues(repo, issues)
  await closeGeneratedIssues(repo, generatedStamp)
}
if (typeof require !== 'undefined' && require.main === module) {
  main()
}
